///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Calculator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CalculatorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("121eadf2-242b-4782-80bf-091c37156b3c")]
    public partial class CalculatorRepository : RepoGenBaseFolder
    {
        static CalculatorRepository instance = new CalculatorRepository();
        CalculatorRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the CalculatorRepository element repository.
        /// </summary>
        [RepositoryFolder("121eadf2-242b-4782-80bf-091c37156b3c")]
        public static CalculatorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CalculatorRepository() 
            : base("CalculatorRepository", "/", null, 0, false, "121eadf2-242b-4782-80bf-091c37156b3c", ".\\RepositoryImages\\CalculatorRepository121eadf2.rximgres")
        {
            _calculator = new CalculatorRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("121eadf2-242b-4782-80bf-091c37156b3c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("4671e6c1-1236-435b-ba70-f91455720e51")]
        public virtual CalculatorRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CalculatorRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("4671e6c1-1236-435b-ba70-f91455720e51")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _multiplybuttonInfo;
            RepoItemInfo _text5Info;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _text6Info;
            RepoItemInfo _equalbuttonInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "4671e6c1-1236-435b-ba70-f91455720e51", "")
            {
                _multiplybuttonInfo = new RepoItemInfo(this, "MultiplyButton", "?/?/container[@automationid='StandardOperators']/button[@automationid='multiplyButton']", ".//button[@automationid='multiplyButton']", 30000, null, "c0d46a0a-563a-4bc0-9f27-2b3a5d179a2e");
                _text5Info = new RepoItemInfo(this, "Text5", ".//button[@automationid='num5Button']/text[@name='5']", ".//text[@name='5']", 30000, null, "9bf44688-1f5e-4d14-a65b-b69b42f89e89");
                _sometextInfo = new RepoItemInfo(this, "SomeText", ".//button[@automationid='equalButton']/text[@name='']", ".//text[@name='']", 30000, null, "963501be-d324-4c32-81a1-9e87781e63f6");
                _text1Info = new RepoItemInfo(this, "Text1", ".//button[@automationid='num1Button']/text[@name='1']", ".//text[@name='1']", 30000, null, "bb943713-336d-4335-8049-fcf7cc815bdd");
                _text6Info = new RepoItemInfo(this, "Text6", ".//button[@automationid='num6Button']/text[@name='6']", ".//text[@name='6']", 30000, null, "8f0a4e8a-40ac-42ac-b79c-18fe4749e799");
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", "?/?/container[@automationid='StandardOperators']/button[@automationid='equalButton']", ".//button[@automationid='equalButton']", 30000, null, "8f38c358-0a36-4674-809b-c5655fea426d");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@automationid='Close']", "?/?/button[@automationid='Close']", 30000, null, "1aea28fc-09d5-4474-9eec-bd0be2580cd5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4671e6c1-1236-435b-ba70-f91455720e51")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4671e6c1-1236-435b-ba70-f91455720e51")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MultiplyButton item.
            /// </summary>
            [RepositoryItem("c0d46a0a-563a-4bc0-9f27-2b3a5d179a2e")]
            public virtual Ranorex.Button MultiplyButton
            {
                get
                {
                    return _multiplybuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MultiplyButton item info.
            /// </summary>
            [RepositoryItemInfo("c0d46a0a-563a-4bc0-9f27-2b3a5d179a2e")]
            public virtual RepoItemInfo MultiplyButtonInfo
            {
                get
                {
                    return _multiplybuttonInfo;
                }
            }

            /// <summary>
            /// The Text5 item.
            /// </summary>
            [RepositoryItem("9bf44688-1f5e-4d14-a65b-b69b42f89e89")]
            public virtual Ranorex.Text Text5
            {
                get
                {
                    return _text5Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text5 item info.
            /// </summary>
            [RepositoryItemInfo("9bf44688-1f5e-4d14-a65b-b69b42f89e89")]
            public virtual RepoItemInfo Text5Info
            {
                get
                {
                    return _text5Info;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("963501be-d324-4c32-81a1-9e87781e63f6")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("963501be-d324-4c32-81a1-9e87781e63f6")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("bb943713-336d-4335-8049-fcf7cc815bdd")]
            public virtual Ranorex.Text Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("bb943713-336d-4335-8049-fcf7cc815bdd")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The Text6 item.
            /// </summary>
            [RepositoryItem("8f0a4e8a-40ac-42ac-b79c-18fe4749e799")]
            public virtual Ranorex.Text Text6
            {
                get
                {
                    return _text6Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text6 item info.
            /// </summary>
            [RepositoryItemInfo("8f0a4e8a-40ac-42ac-b79c-18fe4749e799")]
            public virtual RepoItemInfo Text6Info
            {
                get
                {
                    return _text6Info;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("8f38c358-0a36-4674-809b-c5655fea426d")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("8f38c358-0a36-4674-809b-c5655fea426d")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("1aea28fc-09d5-4474-9eec-bd0be2580cd5")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("1aea28fc-09d5-4474-9eec-bd0be2580cd5")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
